import { RootState, useAppDispatch } from '@/app/store'
import NoMoreData from '@/components/common/NoMoreData'
import UserCard from '@/components/common/UserCard'
import Navbar from '@/components/nav/Navbar'
import FlexCenterBox from '@/components/styled/FlexCenterBox'
import { trpc } from '@/utils/trpc'
import { Box, CircularProgress } from '@mui/material'
import Head from 'next/head'

import { useSelector } from 'react-redux'

export default function Home() {
  const usersQuery = trpc.user.users.useQuery()
  const currentUser = useSelector((state: RootState) => state.user.userInfo)

  const isLoading = usersQuery.isLoading && !usersQuery.data
  const users =
    usersQuery.data?.data.users.filter(
      (user) =>
        user.id !== currentUser?.id &&
        !user.likedBy.find((user) => user.id === currentUser?.id) &&
        !user.dislikedBy.find((user) => user.id === currentUser?.id),
    ) ?? []
  const isNoData = !usersQuery.isLoading && !usersQuery.data

  return (
    <Box>
      <Head>
        <title>Swipe it!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <FlexCenterBox>
          {isNoData ? (
            ' No Data'
          ) : isLoading ? (
            <CircularProgress />
          ) : (
            <>
              {users.map((user) => {
                return <UserCard key={user.id} user={user} />
              })}
              <NoMoreData />
            </>
          )}
        </FlexCenterBox>
      </main>
    </Box>
  )
}
