import Navbar from '@/components/nav/Navbar'
import { trpc } from '@/utils/trpc'
import { Box } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App Haha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <h1>WelcomeHAHA</h1>
      </main>
    </Box>
  )
}
